#!/usr/bin/env bash
set -e

echo "Hello gh-sample-extension!"

# Determine if an executable is in the PATH
if ! type -p node >/dev/null; then
  echo "Node not found on the system" >&2
  exit 1
fi

# Pass arguments through to another command
# gh issue list "$@" -R cli/cli
